import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Search } from "lucide-react";
import { ProductCard } from "@/components/public/product-card";
import { Button } from "@/components/ui/button";
import { getMenu, getPublicSettings } from "@/server/dal/public";

export async function generateMetadata({ params }: { params: Promise<{ category: string }> }): Promise<Metadata> { const { category } = await params; const menu = await getMenu(category); if (!menu[0]) return { title: "Kategori bulunamadı" }; return { title: menu[0].name, description: menu[0].description ?? `${menu[0].name} ürünleri`, alternates: { canonical: `/menu/${category}` } }; }

export default async function CategoryPage({ params }: { params: Promise<{ category: string }> }) { const { category } = await params; const [settings, menu] = await Promise.all([getPublicSettings(), getMenu(category)]); const item = menu[0]; if (!settings || !item) notFound(); return <div className="container-shell py-10 sm:py-16"><Button asChild variant="ghost" className="-ml-3"><Link href="/menu"><ArrowLeft /> Tüm menü</Link></Button><div className="mt-7 min-w-0 border-b pb-7"><p className="eyebrow">Menü kategorisi</p><div className="mt-2 flex min-w-0 flex-col items-start gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><h1 className="break-words font-heading text-4xl font-bold tracking-tight sm:text-6xl">{item.name}</h1>{item.description ? <p className="mt-3 max-w-2xl break-words text-base leading-7 text-muted-foreground">{item.description}</p> : null}</div><span className="shrink-0 rounded-full bg-muted px-3 py-1 text-xs font-semibold text-muted-foreground">{item.products.length} ürün</span></div></div>{item.products.length ? <div className="mt-6 grid min-w-0 gap-4 sm:grid-cols-2 sm:gap-5 lg:grid-cols-3">{item.products.map((product) => <ProductCard key={product.id} product={product} currency={settings.currency} locale={settings.locale} />)}</div> : <div className="surface-panel mt-10 border-dashed py-14 text-center"><Search className="mx-auto size-7 text-muted-foreground" /><h2 className="mt-4 text-xl font-bold">Şu anda ürün bulunmuyor</h2><p className="mt-2 text-muted-foreground">Diğer kategorilerimize göz atabilirsiniz.</p></div>}</div>; }