"use client";

import { useActionState, useState } from "react";
import { RestaurantImage } from "@/components/public/restaurant-image";
import { saveProductAction } from "@/features/admin/actions";
import { INITIAL_ACTION_STATE } from "@/lib/action-state";
import { formatPrice } from "@/lib/format";
import { ActionFeedback, FieldError } from "@/components/admin/action-feedback";
import { SubmitButton } from "@/components/admin/submit-button";
import { ImageInput } from "@/components/admin/image-input";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Option = { id: string; name: string };
type ProductInitial = { id?: string; name?: string; description?: string; shortDescription?: string | null; price?: string; oldPrice?: string | null; badge?: string | null; categoryId?: string; sortOrder?: number; isActive?: boolean; isFeatured?: boolean; isAvailable?: boolean; imageUrl?: string | null };

export function ProductForm({ categories, initial = {} }: { categories: Option[]; initial?: ProductInitial }) {
  const [state, action] = useActionState(saveProductAction, INITIAL_ACTION_STATE);
  const [preview, setPreview] = useState({ name: initial.name ?? "Ürün adı", description: initial.description ?? "Ürün açıklaması burada görünecek.", price: initial.price ?? "0", badge: initial.badge ?? "" });
  function updatePreview(event: React.FormEvent<HTMLFormElement>) { const data = new FormData(event.currentTarget); setPreview({ name: String(data.get("name") || "Ürün adı"), description: String(data.get("description") || "Ürün açıklaması burada görünecek."), price: String(data.get("price") || "0"), badge: String(data.get("badge") || "") }); }

  return <form action={action} onInput={updatePreview} className="grid gap-5">{initial.id ? <input type="hidden" name="id" value={initial.id} /> : null}<ActionFeedback state={state} /><div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_19rem]"><div className="grid gap-5">
    <section className="grid gap-4 rounded-xl border bg-card p-5"><div><h2 className="text-lg font-bold">Ürün bilgileri</h2><p className="mt-1 text-sm text-muted-foreground">Müşterinin menüde göreceği temel bilgiler.</p></div><div className="grid gap-2"><Label htmlFor="name">Ürün adı</Label><Input id="name" name="name" defaultValue={initial.name} maxLength={100} required /><FieldError errors={state.fieldErrors?.name} /></div><div className="grid gap-2"><Label htmlFor="description">Açıklama</Label><Textarea id="description" name="description" defaultValue={initial.description} rows={4} maxLength={800} required /><FieldError errors={state.fieldErrors?.description} /></div><div className="grid gap-2"><Label htmlFor="shortDescription">Kısa açıklama <span className="font-normal text-muted-foreground">(isteğe bağlı)</span></Label><Input id="shortDescription" name="shortDescription" defaultValue={initial.shortDescription ?? ""} maxLength={180} /></div></section>
    <section className="grid gap-4 rounded-xl border bg-card p-5"><div><h2 className="text-lg font-bold">Fiyat ve kategori</h2><p className="mt-1 text-sm text-muted-foreground">Müşterinin göreceği fiyatı ve menü kategorisini belirleyin.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="grid gap-2"><Label htmlFor="price">Fiyat (₺)</Label><Input id="price" name="price" type="number" min="0.01" max="999999.99" step="0.01" defaultValue={initial.price} required /><FieldError errors={state.fieldErrors?.price} /></div><div className="grid gap-2"><Label htmlFor="oldPrice">Eski fiyat <span className="font-normal text-muted-foreground">(isteğe bağlı)</span></Label><Input id="oldPrice" name="oldPrice" type="number" min="0.01" step="0.01" defaultValue={initial.oldPrice ?? ""} /></div><div className="grid gap-2"><Label htmlFor="categoryId">Kategori</Label><select id="categoryId" name="categoryId" defaultValue={initial.categoryId} className="min-h-11 rounded-lg border bg-transparent px-3" required><option value="">Kategori seçin</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><FieldError errors={state.fieldErrors?.categoryId} /></div><div className="grid gap-2"><Label htmlFor="sortOrder">Görünme sırası</Label><Input id="sortOrder" name="sortOrder" type="number" min="0" defaultValue={initial.sortOrder ?? 0} /></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="badge">Kısa rozet <span className="font-normal text-muted-foreground">(isteğe bağlı)</span></Label><Input id="badge" name="badge" defaultValue={initial.badge ?? ""} placeholder="Yeni, Acılı, Avantajlı" maxLength={30} /></div></div></section>
    <section className="grid gap-4 rounded-xl border bg-card p-5"><div><h2 className="text-lg font-bold">Görsel ve satış durumu</h2><p className="mt-1 text-sm text-muted-foreground">4:3 oranlı, aydınlık bir ürün fotoğrafı önerilir.</p></div><ImageInput name="image" label="Ürün görseli" currentUrl={initial.imageUrl} removeName="removeImage" /><div className="grid gap-2 sm:grid-cols-3"><label className="flex min-h-12 items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" name="isActive" defaultChecked={initial.isActive ?? true} /> Menüde göster</label><label className="flex min-h-12 items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" name="isAvailable" defaultChecked={initial.isAvailable ?? true} /> Şu anda satışta</label><label className="flex min-h-12 items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" name="isFeatured" defaultChecked={initial.isFeatured ?? false} /> Öne çıkar</label></div></section>
  </div><aside className="sticky top-20 hidden lg:block"><p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-muted-foreground">Menü önizlemesi</p><article className="overflow-hidden rounded-xl border bg-card shadow-sm"><div className="relative aspect-[4/3] bg-muted"><RestaurantImage src={initial.imageUrl} alt="Menü kartı önizlemesi" fill sizes="304px" className="object-cover" />{preview.badge ? <span className="absolute left-2 top-2 rounded-full bg-white px-2 py-1 text-xs font-bold">{preview.badge}</span> : null}</div><div className="p-4"><h3 className="font-heading text-xl font-semibold">{preview.name}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-muted-foreground">{preview.description}</p><strong className="mt-3 block text-primary">{formatPrice(Number(preview.price) || 0)}</strong></div></article></aside></div>
    <div className="sticky bottom-3 z-20 flex justify-end rounded-xl border bg-background/92 p-3 shadow-lg backdrop-blur"><SubmitButton>{initial.id ? "Değişiklikleri kaydet" : "Ürünü ekle"}</SubmitButton></div>
  </form>;
}
