import Image from "next/image";
import Link from "next/link";
import { Copy, Edit3, PackageOpen, Plus, Search } from "lucide-react";
import { ConfirmDelete } from "@/components/admin/confirm-delete";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { deleteProductAction, duplicateProductAction, setCategoryAvailabilityAction, toggleProductAvailabilityAction } from "@/features/admin/actions";
import { formatPrice } from "@/lib/format";
import { getAdminDb } from "@/server/dal/admin";

type Params = { q?: string; category?: string; status?: string; success?: string };

export default async function ProductsPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams;
  const query = (params.q ?? "").trim().slice(0, 100);
  const categoryId = params.category && params.category.length <= 64 ? params.category : "";
  const status = ["available", "unavailable"].includes(params.status ?? "") ? params.status : "";
  const db = await getAdminDb();
  const [categories, products] = await Promise.all([db.category.findMany({ where: { archivedAt: null }, orderBy: { sortOrder: "asc" } }), db.product.findMany({ where: { archivedAt: null, ...(query ? { name: { contains: query, mode: "insensitive" as const } } : {}), ...(categoryId ? { categoryId } : {}), ...(status === "available" ? { isAvailable: true } : status === "unavailable" ? { isAvailable: false } : {}) }, include: { category: true }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] })]);

  return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="eyebrow">Menü yönetimi</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">Ürünler</h1><p className="mt-1 text-sm text-muted-foreground">Fiyatı, görünürlüğü ve güncel mevcudiyeti yönetin.</p></div><Button asChild><Link href="/admin/products/new"><Plus />Yeni ürün</Link></Button></div>
    {params.success === "deleted" ? <div className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800">Ürün arşivlendi ve menüden kaldırıldı.</div> : null}
    <form className="grid gap-2 rounded-xl border bg-card p-3 sm:grid-cols-[1fr_200px_160px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input name="q" defaultValue={query} maxLength={100} placeholder="Ürün ara…" className="pl-9" /></div><select aria-label="Kategori filtresi" name="category" defaultValue={categoryId} className="min-h-11 rounded-lg border bg-background px-3 text-sm"><option value="">Tüm kategoriler</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><select aria-label="Satış durumu filtresi" name="status" defaultValue={status} className="min-h-11 rounded-lg border bg-background px-3 text-sm"><option value="">Tüm durumlar</option><option value="available">Satışta</option><option value="unavailable">Tükendi</option></select><Button type="submit" variant="outline">Filtrele</Button></form>
    {categoryId ? <div className="flex flex-wrap items-center gap-2 rounded-xl border bg-card p-3 text-sm"><strong className="mr-auto">Seçili kategorideki tüm ürünler</strong>{[[false, "Bugün tükendi"], [true, "Yeniden satışta"]].map(([available, label]) => <form action={setCategoryAvailabilityAction} key={String(available)}><input type="hidden" name="categoryId" value={categoryId} /><input type="hidden" name="isAvailable" value={String(available)} /><Button type="submit" size="sm" variant="outline">{label}</Button></form>)}</div> : null}
    {products.length ? <div className="overflow-hidden rounded-xl border bg-card"><div className="hidden grid-cols-[minmax(0,1.5fr)_1fr_7rem_10rem_18rem] gap-3 border-b bg-muted/60 px-4 py-2 text-xs font-bold uppercase tracking-wider text-muted-foreground lg:grid"><span>Ürün</span><span>Kategori</span><span>Fiyat</span><span>Durum</span><span className="text-right">İşlemler</span></div><div className="divide-y">{products.map((product) => <article key={product.id} className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1.5fr)_1fr_7rem_10rem_18rem] lg:items-center lg:gap-3"><div className="flex min-w-0 items-center gap-3">{product.imageUrl ? <Image src={product.imageUrl} alt="" width={64} height={64} className="size-16 shrink-0 rounded-lg object-cover" /> : <div className="size-16 shrink-0 rounded-lg bg-muted" />}<div className="min-w-0"><h2 className="truncate font-bold">{product.name}</h2><p className="truncate text-xs text-muted-foreground lg:hidden">{product.category.name}</p></div></div><p className="hidden text-sm text-muted-foreground lg:block">{product.category.name}</p><strong>{formatPrice(product.price.toString())}</strong><div className="flex flex-wrap gap-1"><Badge variant={product.isActive ? "secondary" : "outline"}>{product.isActive ? "Yayında" : "Gizli"}</Badge><Badge variant={product.isAvailable ? "secondary" : "destructive"}>{product.isAvailable ? "Mevcut" : "Tükendi"}</Badge></div><div className="flex flex-wrap justify-start gap-1.5 lg:justify-end"><form action={toggleProductAvailabilityAction}><input type="hidden" name="id" value={product.id} /><input type="hidden" name="isAvailable" value={String(!product.isAvailable)} /><Button type="submit" size="sm" variant="outline">{product.isAvailable ? "Bugün tükendi" : "Yeniden mevcut"}</Button></form><Button asChild size="icon" variant="outline" aria-label={`${product.name} ürününü düzenle`}><Link href={`/admin/products/${product.id}`}><Edit3 /></Link></Button><form action={duplicateProductAction}><input type="hidden" name="id" value={product.id} /><Button type="submit" size="icon" variant="outline" aria-label={`${product.name} ürününü kopyala`}><Copy /></Button></form><ConfirmDelete id={product.id} title={`${product.name} arşivlensin mi?`} description="Ürün menüden kaldırılır; geçmiş kayıtlar korunur." action={deleteProductAction} /></div></article>)}</div></div> : <EmptyState icon={PackageOpen} title="Ürün bulunamadı" description="Filtreleri temizleyin veya menüye yeni bir ürün ekleyin." action={<Button asChild><Link href="/admin/products/new"><Plus />Yeni ürün</Link></Button>} />}
  </div>;
}
